[package]
name = "harbor-widget"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
hashbrown = { workspace = true }
slotmap = { workspace = true }
harbor-text = { workspace = true }
wgpu = { workspace = true }
tracing = { workspace = true }
harbor-widget-macros = { workspace = true }
arboard = { workspace = true, optional = true }
winit = { workspace = true, optional = true }

[target."cfg(windows)".dependencies]
windows = { workspace = true, optional = true }

[features]
default = []
winit = ["dep:winit", "dep:windows", "dep:arboard"]
backend-dx12 = []
backend-vulkan = []

[dev-dependencies]
pollster = { workspace = true }
harbor-text = { workspace = true }
