// Bindings generated by `windows-bindgen` 0.62.1

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DesktopAcrylicController(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    DesktopAcrylicController,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(
    DesktopAcrylicController,
    windows::Foundation::IClosable,
    IClosableNotifier,
    ISystemBackdropController,
    ISystemBackdropControllerWithTargets
);
impl DesktopAcrylicController {
    pub fn new() -> windows_core::Result<Self> {
        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
    }
    fn IActivationFactory<
        R,
        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            DesktopAcrylicController,
            windows_core::imp::IGenericFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
    pub fn IsClosed(&self) -> windows_core::Result<bool> {
        let this = &windows_core::Interface::cast::<IClosableNotifier>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsClosed)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveClosed(&self, token: i64) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IClosableNotifier>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveClosed)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn RemoveFrameworkClosed(&self, token: i64) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IClosableNotifier>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveFrameworkClosed)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn FallbackColor(&self) -> windows_core::Result<windows::UI::Color> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).FallbackColor)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetFallbackColor(&self, value: windows::UI::Color) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetFallbackColor)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn LuminosityOpacity(&self) -> windows_core::Result<f32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).LuminosityOpacity)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetLuminosityOpacity(&self, value: f32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetLuminosityOpacity)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn TintColor(&self) -> windows_core::Result<windows::UI::Color> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TintColor)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTintColor(&self, value: windows::UI::Color) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTintColor)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn TintOpacity(&self) -> windows_core::Result<f32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TintOpacity)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTintOpacity(&self, value: f32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTintOpacity)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn ResetProperties(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IDesktopAcrylicController2>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).ResetProperties)(
                windows_core::Interface::as_raw(this),
            )
            .ok()
        }
    }
    pub fn Kind(&self) -> windows_core::Result<DesktopAcrylicKind> {
        let this = &windows_core::Interface::cast::<IDesktopAcrylicController3>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Kind)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetKind(&self, value: DesktopAcrylicKind) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IDesktopAcrylicController3>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).SetKind)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn IsSupported() -> windows_core::Result<bool> {
        Self::IDesktopAcrylicControllerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsSupported)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn SetTargetWithWindowId<P1>(
        &self,
        windowid: WindowId,
        desktopwindowtarget: P1,
    ) -> windows_core::Result<bool>
    where
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropController>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithWindowId)(
                windows_core::Interface::as_raw(this),
                windowid,
                desktopwindowtarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTargetWithCoreWindow<P0, P1>(
        &self,
        corewindow: P0,
        compositiontarget: P1,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<windows::UI::Core::CoreWindow>,
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropController>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithCoreWindow)(
                windows_core::Interface::as_raw(this),
                corewindow.param().abi(),
                compositiontarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn State(&self) -> windows_core::Result<SystemBackdropState> {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).State)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn AddSystemBackdropTarget<P0>(
        &self,
        systembackdroptarget: P0,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<ICompositionSupportsSystemBackdrop>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).AddSystemBackdropTarget)(
                windows_core::Interface::as_raw(this),
                systembackdroptarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveAllSystemBackdropTargets(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveAllSystemBackdropTargets)(
                windows_core::Interface::as_raw(this),
            )
            .ok()
        }
    }
    pub fn RemoveSystemBackdropTarget<P0>(
        &self,
        systembackdroptarget: P0,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<ICompositionSupportsSystemBackdrop>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RemoveSystemBackdropTarget)(
                windows_core::Interface::as_raw(this),
                systembackdroptarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetSystemBackdropConfiguration<P0>(&self, configuration: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<SystemBackdropConfiguration>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).SetSystemBackdropConfiguration)(
                windows_core::Interface::as_raw(this),
                configuration.param().abi(),
            )
            .ok()
        }
    }
    pub fn StateChanged<P0>(&self, handler: P0) -> windows_core::Result<i64>
    where
        P0: windows_core::Param<
                windows::Foundation::TypedEventHandler<
                    ISystemBackdropControllerWithTargets,
                    windows_core::IInspectable,
                >,
            >,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).StateChanged)(
                windows_core::Interface::as_raw(this),
                handler.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveStateChanged(&self, token: i64) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveStateChanged)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    fn IDesktopAcrylicControllerStatics<
        R,
        F: FnOnce(&IDesktopAcrylicControllerStatics) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            DesktopAcrylicController,
            IDesktopAcrylicControllerStatics,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for DesktopAcrylicController {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IDesktopAcrylicController>();
}
unsafe impl windows_core::Interface for DesktopAcrylicController {
    type Vtable = <IDesktopAcrylicController as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IDesktopAcrylicController as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for DesktopAcrylicController {
    const NAME: &'static str = "Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController";
}
unsafe impl Send for DesktopAcrylicController {}
unsafe impl Sync for DesktopAcrylicController {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct DesktopAcrylicKind(pub i32);
impl DesktopAcrylicKind {
    pub const Default: Self = Self(0i32);
    pub const Base: Self = Self(1i32);
    pub const Thin: Self = Self(2i32);
}
impl windows_core::TypeKind for DesktopAcrylicKind {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for DesktopAcrylicKind {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicKind;i4)",
    );
}
windows_core::imp::define_interface!(
    IClosableNotifier,
    IClosableNotifier_Vtbl,
    0x2989e93b_ed0f_5e79_90f2_eac592fc6e6a
);
impl windows_core::RuntimeType for IClosableNotifier {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    IClosableNotifier,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl IClosableNotifier {
    pub fn IsClosed(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsClosed)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveClosed(&self, token: i64) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveClosed)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn RemoveFrameworkClosed(&self, token: i64) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveFrameworkClosed)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeName for IClosableNotifier {
    const NAME: &'static str = "Microsoft.UI.IClosableNotifier";
}
pub trait IClosableNotifier_Impl: windows_core::IUnknownImpl {
    fn IsClosed(&self) -> windows_core::Result<bool>;
    fn RemoveClosed(&self, token: i64) -> windows_core::Result<()>;
    fn RemoveFrameworkClosed(&self, token: i64) -> windows_core::Result<()>;
}
impl IClosableNotifier_Vtbl {
    pub const fn new<Identity: IClosableNotifier_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn IsClosed<
            Identity: IClosableNotifier_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IClosableNotifier_Impl::IsClosed(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RemoveClosed<
            Identity: IClosableNotifier_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            token: i64,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IClosableNotifier_Impl::RemoveClosed(this, token).into()
            }
        }
        unsafe extern "system" fn RemoveFrameworkClosed<
            Identity: IClosableNotifier_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            token: i64,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IClosableNotifier_Impl::RemoveFrameworkClosed(this, token).into()
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IClosableNotifier, OFFSET>(),
            IsClosed: IsClosed::<Identity, OFFSET>,
            Closed: 0,
            RemoveClosed: RemoveClosed::<Identity, OFFSET>,
            FrameworkClosed: 0,
            RemoveFrameworkClosed: RemoveFrameworkClosed::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IClosableNotifier as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IClosableNotifier_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub IsClosed:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    Closed: usize,
    pub RemoveClosed:
        unsafe extern "system" fn(*mut core::ffi::c_void, i64) -> windows_core::HRESULT,
    FrameworkClosed: usize,
    pub RemoveFrameworkClosed:
        unsafe extern "system" fn(*mut core::ffi::c_void, i64) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ICompositionSupportsSystemBackdrop,
    ICompositionSupportsSystemBackdrop_Vtbl,
    0x397dafe4_b6c2_5bb9_951d_f5707de8b7bc
);
impl windows_core::RuntimeType for ICompositionSupportsSystemBackdrop {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    ICompositionSupportsSystemBackdrop,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl ICompositionSupportsSystemBackdrop {
    pub fn SystemBackdrop(
        &self,
    ) -> windows_core::Result<windows::UI::Composition::CompositionBrush> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SystemBackdrop)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn SetSystemBackdrop<P0>(&self, value: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<windows::UI::Composition::CompositionBrush>,
    {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetSystemBackdrop)(
                windows_core::Interface::as_raw(this),
                value.param().abi(),
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeName for ICompositionSupportsSystemBackdrop {
    const NAME: &'static str = "Microsoft.UI.Composition.ICompositionSupportsSystemBackdrop";
}
pub trait ICompositionSupportsSystemBackdrop_Impl: windows_core::IUnknownImpl {
    fn SystemBackdrop(&self) -> windows_core::Result<windows::UI::Composition::CompositionBrush>;
    fn SetSystemBackdrop(
        &self,
        value: windows_core::Ref<'_, windows::UI::Composition::CompositionBrush>,
    ) -> windows_core::Result<()>;
}
impl ICompositionSupportsSystemBackdrop_Vtbl {
    pub const fn new<Identity: ICompositionSupportsSystemBackdrop_Impl, const OFFSET: isize>()
    -> Self {
        unsafe extern "system" fn SystemBackdrop<
            Identity: ICompositionSupportsSystemBackdrop_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ICompositionSupportsSystemBackdrop_Impl::SystemBackdrop(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSystemBackdrop<
            Identity: ICompositionSupportsSystemBackdrop_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ICompositionSupportsSystemBackdrop_Impl::SetSystemBackdrop(
                    this,
                    core::mem::transmute_copy(&value),
                )
                .into()
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                ICompositionSupportsSystemBackdrop,
                OFFSET,
            >(),
            SystemBackdrop: SystemBackdrop::<Identity, OFFSET>,
            SetSystemBackdrop: SetSystemBackdrop::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<ICompositionSupportsSystemBackdrop as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct ICompositionSupportsSystemBackdrop_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub SystemBackdrop: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetSystemBackdrop: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IDesktopAcrylicController,
    IDesktopAcrylicController_Vtbl,
    0x7c20a6af_8eb3_5f08_bdfc_6d35e35dfe45
);
impl windows_core::RuntimeType for IDesktopAcrylicController {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IDesktopAcrylicController_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub FallbackColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub SetFallbackColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub LuminosityOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut f32) -> windows_core::HRESULT,
    pub SetLuminosityOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
    pub TintColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub SetTintColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub TintOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut f32) -> windows_core::HRESULT,
    pub SetTintOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IDesktopAcrylicController2,
    IDesktopAcrylicController2_Vtbl,
    0x88e0a368_dfc7_5971_a50b_40df5aa5f5c2
);
impl windows_core::RuntimeType for IDesktopAcrylicController2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IDesktopAcrylicController2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub ResetProperties: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IDesktopAcrylicController3,
    IDesktopAcrylicController3_Vtbl,
    0x30d917e6_02d3_59ca_b440_bf9d2e7cc140
);
impl windows_core::RuntimeType for IDesktopAcrylicController3 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IDesktopAcrylicController3_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Kind: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut DesktopAcrylicKind,
    ) -> windows_core::HRESULT,
    pub SetKind: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        DesktopAcrylicKind,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IDesktopAcrylicControllerStatics,
    IDesktopAcrylicControllerStatics_Vtbl,
    0xa9e8f790_79ef_5416_9b67_6bcfe867c8b7
);
impl windows_core::RuntimeType for IDesktopAcrylicControllerStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IDesktopAcrylicControllerStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub IsSupported:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IMicaController,
    IMicaController_Vtbl,
    0x2de996a9_0a2a_5889_a89c_1f84060a8cab
);
impl windows_core::RuntimeType for IMicaController {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IMicaController_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub FallbackColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub SetFallbackColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub LuminosityOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut f32) -> windows_core::HRESULT,
    pub SetLuminosityOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
    pub TintColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub SetTintColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        windows::UI::Color,
    ) -> windows_core::HRESULT,
    pub TintOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut f32) -> windows_core::HRESULT,
    pub SetTintOpacity:
        unsafe extern "system" fn(*mut core::ffi::c_void, f32) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IMicaController2,
    IMicaController2_Vtbl,
    0xf1ed4a52_d9ca_506e_9586_caaefd3aa971
);
impl windows_core::RuntimeType for IMicaController2 {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IMicaController2_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Kind:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut MicaKind) -> windows_core::HRESULT,
    pub SetKind:
        unsafe extern "system" fn(*mut core::ffi::c_void, MicaKind) -> windows_core::HRESULT,
    pub ResetProperties: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IMicaControllerStatics,
    IMicaControllerStatics_Vtbl,
    0x7d85d834_d514_5250_b7c4_0b7850d1efdc
);
impl windows_core::RuntimeType for IMicaControllerStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct IMicaControllerStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub IsSupported:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ISystemBackdropConfiguration,
    ISystemBackdropConfiguration_Vtbl,
    0xebcce1b9_0e0c_5431_ab0e_00f3f0669962
);
impl windows_core::RuntimeType for ISystemBackdropConfiguration {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
#[doc(hidden)]
pub struct ISystemBackdropConfiguration_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub HighContrastBackgroundColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetHighContrastBackgroundColor: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub IsHighContrast:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    pub SetIsHighContrast:
        unsafe extern "system" fn(*mut core::ffi::c_void, bool) -> windows_core::HRESULT,
    pub IsInputActive:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    pub SetIsInputActive:
        unsafe extern "system" fn(*mut core::ffi::c_void, bool) -> windows_core::HRESULT,
    pub Theme: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut SystemBackdropTheme,
    ) -> windows_core::HRESULT,
    pub SetTheme: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        SystemBackdropTheme,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ISystemBackdropController,
    ISystemBackdropController_Vtbl,
    0x5632d76c_0b74_5b52_aa33_80262068aeb2
);
impl windows_core::RuntimeType for ISystemBackdropController {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    ISystemBackdropController,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(ISystemBackdropController, windows::Foundation::IClosable);
impl ISystemBackdropController {
    pub fn SetTargetWithWindowId<P1>(
        &self,
        windowid: WindowId,
        desktopwindowtarget: P1,
    ) -> windows_core::Result<bool>
    where
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithWindowId)(
                windows_core::Interface::as_raw(this),
                windowid,
                desktopwindowtarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTargetWithCoreWindow<P0, P1>(
        &self,
        corewindow: P0,
        compositiontarget: P1,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<windows::UI::Core::CoreWindow>,
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithCoreWindow)(
                windows_core::Interface::as_raw(this),
                corewindow.param().abi(),
                compositiontarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
}
impl windows_core::RuntimeName for ISystemBackdropController {
    const NAME: &'static str = "Microsoft.UI.Composition.SystemBackdrops.ISystemBackdropController";
}
pub trait ISystemBackdropController_Impl: windows::Foundation::IClosable_Impl {
    fn SetTargetWithWindowId(
        &self,
        windowId: &WindowId,
        desktopWindowTarget: windows_core::Ref<'_, windows::UI::Composition::CompositionTarget>,
    ) -> windows_core::Result<bool>;
    fn SetTargetWithCoreWindow(
        &self,
        coreWindow: windows_core::Ref<'_, windows::UI::Core::CoreWindow>,
        compositionTarget: windows_core::Ref<'_, windows::UI::Composition::CompositionTarget>,
    ) -> windows_core::Result<bool>;
}
impl ISystemBackdropController_Vtbl {
    pub const fn new<Identity: ISystemBackdropController_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn SetTargetWithWindowId<
            Identity: ISystemBackdropController_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            windowid: WindowId,
            desktopwindowtarget: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ISystemBackdropController_Impl::SetTargetWithWindowId(
                    this,
                    core::mem::transmute(&windowid),
                    core::mem::transmute_copy(&desktopwindowtarget),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetTargetWithCoreWindow<
            Identity: ISystemBackdropController_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            corewindow: *mut core::ffi::c_void,
            compositiontarget: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ISystemBackdropController_Impl::SetTargetWithCoreWindow(
                    this,
                    core::mem::transmute_copy(&corewindow),
                    core::mem::transmute_copy(&compositiontarget),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                ISystemBackdropController,
                OFFSET,
            >(),
            SetTargetWithWindowId: SetTargetWithWindowId::<Identity, OFFSET>,
            SetTargetWithCoreWindow: SetTargetWithCoreWindow::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<ISystemBackdropController as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct ISystemBackdropController_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub SetTargetWithWindowId: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        WindowId,
        *mut core::ffi::c_void,
        *mut bool,
    ) -> windows_core::HRESULT,
    pub SetTargetWithCoreWindow: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut bool,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    ISystemBackdropControllerWithTargets,
    ISystemBackdropControllerWithTargets_Vtbl,
    0x9c56fe7c_98eb_5f89_ad97_dad57fc30c8c
);
impl windows_core::RuntimeType for ISystemBackdropControllerWithTargets {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    ISystemBackdropControllerWithTargets,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(
    ISystemBackdropControllerWithTargets,
    windows::Foundation::IClosable,
    ISystemBackdropController
);
impl ISystemBackdropControllerWithTargets {
    pub fn State(&self) -> windows_core::Result<SystemBackdropState> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).State)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn AddSystemBackdropTarget<P0>(
        &self,
        systembackdroptarget: P0,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<ICompositionSupportsSystemBackdrop>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).AddSystemBackdropTarget)(
                windows_core::Interface::as_raw(this),
                systembackdroptarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveAllSystemBackdropTargets(&self) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveAllSystemBackdropTargets)(
                windows_core::Interface::as_raw(this),
            )
            .ok()
        }
    }
    pub fn RemoveSystemBackdropTarget<P0>(
        &self,
        systembackdroptarget: P0,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<ICompositionSupportsSystemBackdrop>,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RemoveSystemBackdropTarget)(
                windows_core::Interface::as_raw(this),
                systembackdroptarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetSystemBackdropConfiguration<P0>(&self, configuration: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<SystemBackdropConfiguration>,
    {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetSystemBackdropConfiguration)(
                windows_core::Interface::as_raw(this),
                configuration.param().abi(),
            )
            .ok()
        }
    }
    pub fn StateChanged<P0>(&self, handler: P0) -> windows_core::Result<i64>
    where
        P0: windows_core::Param<
                windows::Foundation::TypedEventHandler<
                    ISystemBackdropControllerWithTargets,
                    windows_core::IInspectable,
                >,
            >,
    {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).StateChanged)(
                windows_core::Interface::as_raw(this),
                handler.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveStateChanged(&self, token: i64) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveStateChanged)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
    pub fn SetTargetWithWindowId<P1>(
        &self,
        windowid: WindowId,
        desktopwindowtarget: P1,
    ) -> windows_core::Result<bool>
    where
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropController>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithWindowId)(
                windows_core::Interface::as_raw(this),
                windowid,
                desktopwindowtarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTargetWithCoreWindow<P0, P1>(
        &self,
        corewindow: P0,
        compositiontarget: P1,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<windows::UI::Core::CoreWindow>,
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropController>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithCoreWindow)(
                windows_core::Interface::as_raw(this),
                corewindow.param().abi(),
                compositiontarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
}
impl windows_core::RuntimeName for ISystemBackdropControllerWithTargets {
    const NAME: &'static str =
        "Microsoft.UI.Composition.SystemBackdrops.ISystemBackdropControllerWithTargets";
}
pub trait ISystemBackdropControllerWithTargets_Impl:
    windows::Foundation::IClosable_Impl + ISystemBackdropController_Impl
{
    fn State(&self) -> windows_core::Result<SystemBackdropState>;
    fn AddSystemBackdropTarget(
        &self,
        systemBackdropTarget: windows_core::Ref<'_, ICompositionSupportsSystemBackdrop>,
    ) -> windows_core::Result<bool>;
    fn RemoveAllSystemBackdropTargets(&self) -> windows_core::Result<()>;
    fn RemoveSystemBackdropTarget(
        &self,
        systemBackdropTarget: windows_core::Ref<'_, ICompositionSupportsSystemBackdrop>,
    ) -> windows_core::Result<bool>;
    fn SetSystemBackdropConfiguration(
        &self,
        configuration: windows_core::Ref<'_, SystemBackdropConfiguration>,
    ) -> windows_core::Result<()>;
    fn StateChanged(
        &self,
        handler: windows_core::Ref<
            '_,
            windows::Foundation::TypedEventHandler<
                ISystemBackdropControllerWithTargets,
                windows_core::IInspectable,
            >,
        >,
    ) -> windows_core::Result<i64>;
    fn RemoveStateChanged(&self, token: i64) -> windows_core::Result<()>;
}
impl ISystemBackdropControllerWithTargets_Vtbl {
    pub const fn new<Identity: ISystemBackdropControllerWithTargets_Impl, const OFFSET: isize>()
    -> Self {
        unsafe extern "system" fn State<
            Identity: ISystemBackdropControllerWithTargets_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut SystemBackdropState,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ISystemBackdropControllerWithTargets_Impl::State(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn AddSystemBackdropTarget<
            Identity: ISystemBackdropControllerWithTargets_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            systembackdroptarget: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ISystemBackdropControllerWithTargets_Impl::AddSystemBackdropTarget(
                    this,
                    core::mem::transmute_copy(&systembackdroptarget),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RemoveAllSystemBackdropTargets<
            Identity: ISystemBackdropControllerWithTargets_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ISystemBackdropControllerWithTargets_Impl::RemoveAllSystemBackdropTargets(this)
                    .into()
            }
        }
        unsafe extern "system" fn RemoveSystemBackdropTarget<
            Identity: ISystemBackdropControllerWithTargets_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            systembackdroptarget: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ISystemBackdropControllerWithTargets_Impl::RemoveSystemBackdropTarget(
                    this,
                    core::mem::transmute_copy(&systembackdroptarget),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSystemBackdropConfiguration<
            Identity: ISystemBackdropControllerWithTargets_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            configuration: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ISystemBackdropControllerWithTargets_Impl::SetSystemBackdropConfiguration(
                    this,
                    core::mem::transmute_copy(&configuration),
                )
                .into()
            }
        }
        unsafe extern "system" fn StateChanged<
            Identity: ISystemBackdropControllerWithTargets_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            handler: *mut core::ffi::c_void,
            result__: *mut i64,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ISystemBackdropControllerWithTargets_Impl::StateChanged(
                    this,
                    core::mem::transmute_copy(&handler),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn RemoveStateChanged<
            Identity: ISystemBackdropControllerWithTargets_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            token: i64,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ISystemBackdropControllerWithTargets_Impl::RemoveStateChanged(this, token).into()
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                ISystemBackdropControllerWithTargets,
                OFFSET,
            >(),
            State: State::<Identity, OFFSET>,
            AddSystemBackdropTarget: AddSystemBackdropTarget::<Identity, OFFSET>,
            RemoveAllSystemBackdropTargets: RemoveAllSystemBackdropTargets::<Identity, OFFSET>,
            RemoveSystemBackdropTarget: RemoveSystemBackdropTarget::<Identity, OFFSET>,
            SetSystemBackdropConfiguration: SetSystemBackdropConfiguration::<Identity, OFFSET>,
            StateChanged: StateChanged::<Identity, OFFSET>,
            RemoveStateChanged: RemoveStateChanged::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<ISystemBackdropControllerWithTargets as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct ISystemBackdropControllerWithTargets_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub State: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut SystemBackdropState,
    ) -> windows_core::HRESULT,
    pub AddSystemBackdropTarget: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut bool,
    ) -> windows_core::HRESULT,
    pub RemoveAllSystemBackdropTargets:
        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
    pub RemoveSystemBackdropTarget: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut bool,
    ) -> windows_core::HRESULT,
    pub SetSystemBackdropConfiguration: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub StateChanged: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut i64,
    ) -> windows_core::HRESULT,
    pub RemoveStateChanged:
        unsafe extern "system" fn(*mut core::ffi::c_void, i64) -> windows_core::HRESULT,
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MicaController(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    MicaController,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(
    MicaController,
    windows::Foundation::IClosable,
    IClosableNotifier,
    ISystemBackdropController,
    ISystemBackdropControllerWithTargets
);
impl MicaController {
    pub fn new() -> windows_core::Result<Self> {
        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
    }
    fn IActivationFactory<
        R,
        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            MicaController,
            windows_core::imp::IGenericFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    pub fn Close(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this))
                .ok()
        }
    }
    pub fn IsClosed(&self) -> windows_core::Result<bool> {
        let this = &windows_core::Interface::cast::<IClosableNotifier>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsClosed)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveClosed(&self, token: i64) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IClosableNotifier>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveClosed)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn RemoveFrameworkClosed(&self, token: i64) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IClosableNotifier>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveFrameworkClosed)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    pub fn FallbackColor(&self) -> windows_core::Result<windows::UI::Color> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).FallbackColor)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetFallbackColor(&self, value: windows::UI::Color) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetFallbackColor)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn LuminosityOpacity(&self) -> windows_core::Result<f32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).LuminosityOpacity)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetLuminosityOpacity(&self, value: f32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetLuminosityOpacity)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn TintColor(&self) -> windows_core::Result<windows::UI::Color> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TintColor)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTintColor(&self, value: windows::UI::Color) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTintColor)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn TintOpacity(&self) -> windows_core::Result<f32> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).TintOpacity)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTintOpacity(&self, value: f32) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTintOpacity)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn Kind(&self) -> windows_core::Result<MicaKind> {
        let this = &windows_core::Interface::cast::<IMicaController2>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Kind)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetKind(&self, value: MicaKind) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IMicaController2>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).SetKind)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn ResetProperties(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<IMicaController2>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).ResetProperties)(
                windows_core::Interface::as_raw(this),
            )
            .ok()
        }
    }
    pub fn IsSupported() -> windows_core::Result<bool> {
        Self::IMicaControllerStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsSupported)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn SetTargetWithWindowId<P1>(
        &self,
        windowid: WindowId,
        desktopwindowtarget: P1,
    ) -> windows_core::Result<bool>
    where
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropController>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithWindowId)(
                windows_core::Interface::as_raw(this),
                windowid,
                desktopwindowtarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTargetWithCoreWindow<P0, P1>(
        &self,
        corewindow: P0,
        compositiontarget: P1,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<windows::UI::Core::CoreWindow>,
        P1: windows_core::Param<windows::UI::Composition::CompositionTarget>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropController>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).SetTargetWithCoreWindow)(
                windows_core::Interface::as_raw(this),
                corewindow.param().abi(),
                compositiontarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn State(&self) -> windows_core::Result<SystemBackdropState> {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).State)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn AddSystemBackdropTarget<P0>(
        &self,
        systembackdroptarget: P0,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<ICompositionSupportsSystemBackdrop>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).AddSystemBackdropTarget)(
                windows_core::Interface::as_raw(this),
                systembackdroptarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveAllSystemBackdropTargets(&self) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveAllSystemBackdropTargets)(
                windows_core::Interface::as_raw(this),
            )
            .ok()
        }
    }
    pub fn RemoveSystemBackdropTarget<P0>(
        &self,
        systembackdroptarget: P0,
    ) -> windows_core::Result<bool>
    where
        P0: windows_core::Param<ICompositionSupportsSystemBackdrop>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).RemoveSystemBackdropTarget)(
                windows_core::Interface::as_raw(this),
                systembackdroptarget.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetSystemBackdropConfiguration<P0>(&self, configuration: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<SystemBackdropConfiguration>,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).SetSystemBackdropConfiguration)(
                windows_core::Interface::as_raw(this),
                configuration.param().abi(),
            )
            .ok()
        }
    }
    pub fn StateChanged<P0>(&self, handler: P0) -> windows_core::Result<i64>
    where
        P0: windows_core::Param<
                windows::Foundation::TypedEventHandler<
                    ISystemBackdropControllerWithTargets,
                    windows_core::IInspectable,
                >,
            >,
    {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).StateChanged)(
                windows_core::Interface::as_raw(this),
                handler.param().abi(),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn RemoveStateChanged(&self, token: i64) -> windows_core::Result<()> {
        let this = &windows_core::Interface::cast::<ISystemBackdropControllerWithTargets>(self)?;
        unsafe {
            (windows_core::Interface::vtable(this).RemoveStateChanged)(
                windows_core::Interface::as_raw(this),
                token,
            )
            .ok()
        }
    }
    fn IMicaControllerStatics<R, F: FnOnce(&IMicaControllerStatics) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<MicaController, IMicaControllerStatics> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for MicaController {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IMicaController>();
}
unsafe impl windows_core::Interface for MicaController {
    type Vtable = <IMicaController as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IMicaController as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for MicaController {
    const NAME: &'static str = "Microsoft.UI.Composition.SystemBackdrops.MicaController";
}
unsafe impl Send for MicaController {}
unsafe impl Sync for MicaController {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct MicaKind(pub i32);
impl MicaKind {
    pub const Base: Self = Self(0i32);
    pub const BaseAlt: Self = Self(1i32);
}
impl windows_core::TypeKind for MicaKind {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for MicaKind {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.UI.Composition.SystemBackdrops.MicaKind;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SystemBackdropConfiguration(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    SystemBackdropConfiguration,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl SystemBackdropConfiguration {
    pub fn new() -> windows_core::Result<Self> {
        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
    }
    fn IActivationFactory<
        R,
        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            SystemBackdropConfiguration,
            windows_core::imp::IGenericFactory,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
    pub fn HighContrastBackgroundColor(
        &self,
    ) -> windows_core::Result<windows::Foundation::IReference<windows::UI::Color>> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).HighContrastBackgroundColor)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn SetHighContrastBackgroundColor<P0>(&self, value: P0) -> windows_core::Result<()>
    where
        P0: windows_core::Param<windows::Foundation::IReference<windows::UI::Color>>,
    {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetHighContrastBackgroundColor)(
                windows_core::Interface::as_raw(this),
                value.param().abi(),
            )
            .ok()
        }
    }
    pub fn IsHighContrast(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsHighContrast)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetIsHighContrast(&self, value: bool) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetIsHighContrast)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn IsInputActive(&self) -> windows_core::Result<bool> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsInputActive)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetIsInputActive(&self, value: bool) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetIsInputActive)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
    pub fn Theme(&self) -> windows_core::Result<SystemBackdropTheme> {
        let this = self;
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Theme)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetTheme(&self, value: SystemBackdropTheme) -> windows_core::Result<()> {
        let this = self;
        unsafe {
            (windows_core::Interface::vtable(this).SetTheme)(
                windows_core::Interface::as_raw(this),
                value,
            )
            .ok()
        }
    }
}
impl windows_core::RuntimeType for SystemBackdropConfiguration {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, ISystemBackdropConfiguration>();
}
unsafe impl windows_core::Interface for SystemBackdropConfiguration {
    type Vtable = <ISystemBackdropConfiguration as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <ISystemBackdropConfiguration as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for SystemBackdropConfiguration {
    const NAME: &'static str =
        "Microsoft.UI.Composition.SystemBackdrops.SystemBackdropConfiguration";
}
unsafe impl Send for SystemBackdropConfiguration {}
unsafe impl Sync for SystemBackdropConfiguration {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct SystemBackdropState(pub i32);
impl SystemBackdropState {
    pub const Active: Self = Self(0i32);
    pub const Fallback: Self = Self(1i32);
    pub const HighContrast: Self = Self(2i32);
}
impl windows_core::TypeKind for SystemBackdropState {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for SystemBackdropState {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.UI.Composition.SystemBackdrops.SystemBackdropState;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct SystemBackdropTheme(pub i32);
impl SystemBackdropTheme {
    pub const Default: Self = Self(0i32);
    pub const Light: Self = Self(1i32);
    pub const Dark: Self = Self(2i32);
}
impl windows_core::TypeKind for SystemBackdropTheme {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for SystemBackdropTheme {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme;i4)",
    );
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct WindowId {
    pub Value: u64,
}
impl windows_core::TypeKind for WindowId {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for WindowId {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"struct(Microsoft.UI.WindowId;u8)");
}
